USERNAME = Admin
PASSWORD = admin123
BASEURL = https://opensource-demo.orangehrmlive.com/web/index.php
COLOR = rgba(235, 9, 16, 1)
EMAIL_ALERT = Expected format: admin@example.com
REQUIRED_ALERT = Required
BROWSER = chrome
BROWSER.SIZE=1920x1080
TIMEOUT=10000
MAIN_URL = https://opensource-demo.orangehrmlive.com
selenoidUIUrl=http://192.168.99.101:4444/wd/hub
LEAVE_TYPE_DROPDOWN=CAN - FMLA
INPUT_DATE_FROM=2025-01-06
INPUT_DATE_TO=2025-07-06
LOGIN_STRATEGY=API
DOMAIN=opensource-demo.orangehrmlive.com


